//replaced by new version on 25/05/2019

{
	// if (mixture.ULimiter())
	// {
	// 	//Packed bed index: 0 = stationary
	// 	packedInd = 1.0;
	//
	// 	Info << "Velocity Limiter is active" << endl;
	// 	Info << endl;
	//
	// 	forAll(U.internalField(), celli)
	// 	{
	// 		if (alphad[celli] > alphaMinFriction.value())
	// 		{
	// 			U[celli] *= 0;
	// 			packedInd[celli] = 0.0;
	// 		}
	//
	// 	}
	//
	// 	U.correctBoundaryConditions();
	//
	// }
}
