#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

TurbulenceModels/Allwclean $*
solver/Allwclean $*
solverMULES/Allwclean $*
solverMIXTURE/Allwclean $*

# ----------------------------------------------------------------- end-of-file
