#!/bin/sh


mkdir 1d_profil
python3 -c "import fluidfoam; fluidfoam.create1dprofil('Case1D/', '.', '100', 'Y', ['U.a', 'U.b', 'alpha.a'])"

blockMesh

topoSet

subsetMesh box -patch hole -overwrite


cp -r 0_org 0

funkySetFields -time 0


# Use cellSets to write zoneID
setFields

#decomposePar

overSedDymFoam_rbgh > log&
#mpirun -np 4 overSedDymFoam_rbgh -parallel > log&
