#!/bin/sh


mkdir 1d_profil
python3 -c "import fluidfoam; fluidfoam.create1dprofil('Case1D/', '.', '50', 'Y', ['U.a', 'U.b', 'alpha.a'])"

blockMesh

topoSet

subsetMesh box -patch hole -overwrite


cp -r 0_org 0

funkySetFields -time 0


# Use cellSets to write zoneID
setFields

decomposePar


mpirun -np 4 overSedDymFoam_rbgh -parallel > log&
