#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean libso granularRheologyModelsMix
wclean libso phaseModelMix
wclean libso ppModelMix
wclean libso interfacialModelsMix
wclean libso kineticTheoryModelsMix
wclean

# ----------------------------------------------------------------- end-of-file
